# Generated by Django 3.1 on 2023-09-30 21:29

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_despesaviagem_postagemblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='pais',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
