# Generated by Django 3.1 on 2023-10-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230930_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='DespesaViagem',
        ),
    ]
