# Generated by Django 3.1 on 2023-10-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20231001_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planejamentoviagem',
            name='planejamento',
        ),
        migrations.RemoveField(
            model_name='planejamentoviagem',
            name='viagem',
        ),
        migrations.AddField(
            model_name='postagemblog',
            name='imagem',
            field=models.ImageField(null=True, upload_to='blog_images/'),
        ),
        migrations.DeleteModel(
            name='Planejamento',
        ),
        migrations.DeleteModel(
            name='PlanejamentoViagem',
        ),
    ]
