# Generated by Django 3.1 on 2023-11-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20231102_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarioviagens',
            name='autor',
        ),
    ]
