# Generated by Django 3.1 on 2023-11-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20231102_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarioviagens',
            name='autor',
        ),
    ]
