# Generated by Django 3.1 on 2023-11-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_diarioviagens_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarioviagens',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.pessoa'),
            preserve_default=False,
        ),
    ]
