# Generated by Django 3.1 on 2023-11-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_diarioviagens_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cpf',
        ),
    ]
