# Generated by Django 4.2.7 on 2023-11-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarioviagens',
            name='autor',
        ),
    ]
