# Generated by Django 4.2.7 on 2023-11-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_diarioviagens_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
